version: "3.8"

services:
  app-blue:
    image: finpik-api:latest
    container_name: app-blue
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
    restart: always

  app-green:
    image: finpik-api:latest
    container_name: app-green
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=green
    restart: always
