server:

  port: ${PORT}
  forward-headers-strategy: ${SERVER_FORWARD_HEADERS_STRATEGY}

  servlet:
    session:
      cookie:
        same-site: ${SERVER_SERVLET_SESSION_COOKIE_SAME_SITE}
        secure: ${SERVER_SERVLET_SESSION_COOKIE_SECURE}

spring:
  application:
    name: fin-pik

  graphql:
    graphiql:
      enabled: true

  #Kakao Oauth2 로그인 정보
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            #client-secret: MmDh2LcqW9fYUyvm5yGCEBJpQUz9z6Ty
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - account_email
            client-name: ${KAKAO_CLIENT_NAME}
        provider:
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: id

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  #  #h2
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update    # create, update, none 등
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  #redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    type: none

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true # acks 자동으로 all
    consumer:
      group-id: loan-recommender
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      auto-startup: ${SPRING_KAFKA_LISTENER_AUTO_STARTUP:false}
      concurrency: 3
    admin:
      auto-create: ${SPRING_KAFKA_ADMIN_AUTO_CREATE:false}
      fail-fast: ${SPRING_KAFKA_ADMIN_FAIL_FAST:false}




#Log
logging:
  level:
    org.springframework.security.web.authentication: debug
    org.apache.kafka: error
    org.apache.kafka.clients: warn
    org.springframework.kafka: error
    org.springframework.kafka.listener: warn
    org.springframework.security: info

    # 필터 체인과 보안 디버깅(요청마다 어떤 필터가 적용됐는지)
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.security.web.access.intercept: TRACE
    org.springframework.security.authentication: TRACE

    # OAuth2 클라이언트 전 구간
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.client.web: TRACE
    org.springframework.security.oauth2.client.endpoint: TRACE
    org.springframework.security.oauth2.core: DEBUG

fin-pik:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
  kafka:
    dlqLogFileName: ${KAFKA_DLQ_FILE_NAME}
  domain:
    domain_url: ${DOMAIN_URL}
    front_test_url: ${FRONT_TEST_URL}
    front_app_url: ${FRONT_APP_URL}
  redirect:
    redirect_uri: ${REDIRECT_URI}
  cookie:
    secure: ${COOKIE_SECURE}
    same-site: ${COOKIE_SAME_SITE}   # 프론트도 finpik.o-r.kr이면 Lax로 충분
    max-age-days: ${COOKIE_MAX_AGE_DAYS}
